In [1]:
from numpy import array, sqrt, eye, set_printoptions
from numpy.linalg import inv
from vanloan import numeval

set_printoptions(precision=1, suppress=True)

# System parameters
dt = 5                   # Time interval [second]
q = 0.25                 # Process noise on velocity [meter^2/second^3]

# Dynamic matrix (PV-model)
F = array([[0, 1],
           [0, 0]])

# White noise coefficients
G = array([[0],
           [sqrt(q)]])

# Van Loan numerical solution
phi, Q = numeval(F, G, dt)

# Initial state vector
x = array([[0],          # Position state [meter]
           [1]])         # Velocity state [meter/second]

# Initial state vector covariance matrix
P = array([[2**2, 0],    # Position state variance [meter^2]
           [0, 1**2]])   # Velocity state variance [(meter/second)^2]

In [2]:
# Information matrix and vector initialization
IP = inv(P)
y = IP@x

# Time update (predicion)
M = inv(phi.T)@IP@inv(phi)
yp = (eye(2) - M@inv(inv(Q) + M))@inv(phi.T)@y
IPp = M - M@inv(inv(Q) + M)@M

# Compute predicted state vector and covariance
xp = inv(IPp)@yp
Pp = inv(IPp)

print(xp)
print(Pp)

[[5.]
 [1.]]
[[39.4  8.1]
 [ 8.1  2.3]]


In [3]:
# Position measurement [meter]
z = array([[7]])

# Position measurement variance [meter^2]
R = array([[2**2]])

# Design matrix
H = array([[1, 0]])

# Measurement update (correction)
y = yp + H.T@inv(R)@z
IP = IPp + H.T@inv(R)@H

# Compute estimated state vector and covariance
x = inv(IP)@y
P = inv(IP)

print(x)
print(P)

[[6.8]
 [1.4]]
[[3.6 0.7]
 [0.7 0.7]]
