# Solution {-}

PVA model

In [1]:
from sympy import Matrix, symbols, sqrt, eye, integrate

q, dt = symbols('q \Delta{t}')

F = Matrix([[0, 1, 0],
            [0, 0, 1],
            [0, 0, 0]])

G = Matrix([[0],
            [0],
            [sqrt(q)]])

phi = eye(3) + F*dt + (F*dt)**2/2
phi

Matrix([
[1, \Delta{t}, \Delta{t}**2/2],
[0,         1,      \Delta{t}],
[0,         0,              1]])

In [2]:
# Process noise
Q = integrate(phi@G@G.T@phi.T, dt)
Q

Matrix([
[\Delta{t}**5*q/20, \Delta{t}**4*q/8, \Delta{t}**3*q/6],
[ \Delta{t}**4*q/8, \Delta{t}**3*q/3, \Delta{t}**2*q/2],
[ \Delta{t}**3*q/6, \Delta{t}**2*q/2,      \Delta{t}*q]])

Numerical example

In [3]:
from numpy import array, zeros, arange, set_printoptions
from lib.vanloan import numeval
import matplotlib.pyplot as plt

set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})


# System parameters
dt = 0.1
q = 1e-5

F = array([[0, 1, 0],
           [0, 0, 1],
           [0, 0, 0]])

G = array([[0],
           [0],
           [sqrt(q)]])

# Numerical evaluation
[phi, Q_true] = numeval(F, G, dt)

# Process noise approximation
Q_approx = array([[0, 0, 0],
                  [0, 0, 0],
                  [0, 0, q*dt]])

var_true = []
var_approx = []

# Initial covariance
P = zeros([3, 3])
for i in range(0, 200):
    P = phi@P@phi.T + Q_true
    var_true.append(P)

# Initial covariance
P = zeros([3, 3])
for i in range(0, 200):
    P = phi@P@phi.T + Q_approx
    var_approx.append(P)

# Difference at step 200
print(var_true[199])
print(var_approx[199])

[[1.600 0.200 0.013]
 [0.200 0.027 0.002]
 [0.013 0.002 0.000]]
[[1.580 0.198 0.013]
 [0.198 0.026 0.002]
 [0.013 0.002 0.000]]
