# Solution {-}

A certain linear system is known to satisfy the following differential equation:

\begin{align*}
  &\ddot{x}+10\dot{x}+100x=f(t)\\
  &x(0)=\dot{x}(0)=0\\
\end{align*}

a) The state space differential equation for the random process can be written as:

\begin{equation*}
  \begin{bmatrix}
    \dot{x}_1\\
    \dot{x}_2\\
  \end{bmatrix} =
  \begin{bmatrix}
       0 &  1\\
    -100 &-10\\
  \end{bmatrix}
  \begin{bmatrix}
    x_1\\
    x_2\\
  \end{bmatrix}+
  \begin{bmatrix}
    0\\
    \sqrt{10}\\
  \end{bmatrix} u(t)
\end{equation*}

b) Compute the transition matrix $\phi$ and the covariance matrix $Q$

In [9]:
from numpy import array, sqrt, set_printoptions
from vanloan import numeval

set_printoptions(precision=3, suppress=True)

# Model parameters
dt = 0.2  # seconds
W = 1

# Dynamics matrix
F = array([[0, 1],
           [-100, -10]])

# White noise coefficients
G = array([[0],
           [sqrt(10)]])

# Van Loan (numeric solution)
[phi, Q] = numeval(F, G, dt)

print(phi)
print(Q)

[[ 0.151  0.042]
 [-4.193 -0.269]]
[[0.004 0.009]
 [0.009 0.376]]


In [17]:
[phi, Q] = numeval(F, G, 0.001)
print(phi)
print(Q)

[[ 1.     0.001]
 [-0.1    0.99 ]]
[[0.   0.  ]
 [0.   0.01]]


In [2]:
# Symbolic solution
from sympy import symbols, eye, Matrix, inverse_laplace_transform

s, t = symbols('s t', positive=True)

F = Matrix([[0, 1],
            [-100, -10]])

phi = inverse_laplace_transform((s*eye(2) - F).inv(), s, t)

display(phi)

Matrix([
[sqrt(3)*exp(-5*t)*sin(5*sqrt(3)*t)/3 + exp(-5*t)*cos(5*sqrt(3)*t),                              sqrt(3)*exp(-5*t)*sin(5*sqrt(3)*t)/15],
[                         -20*sqrt(3)*exp(-5*t)*sin(5*sqrt(3)*t)/3, -sqrt(3)*exp(-5*t)*sin(5*sqrt(3)*t)/3 + exp(-5*t)*cos(5*sqrt(3)*t)]])

c) What are the mean square value of $x(t)$ and $\dot{x}(t)$ at t=0.2s

In [3]:
print(f"EX2_x: Q(0, 0) = {Q[0, 0]:.3f}")
print(f"EX2_dot_x: Q(1, 1) = {Q[1, 1]:.3f}")

EX2_x: Q(0, 0) = 0.004
EX2_dot_x: Q(1, 1) = 0.376


The corresponding transfer function $G(s)$ can be written as:
\begin{equation*}
  G(s) = \frac{\sqrt{10}}{s^2 + 10s + 100}
\end{equation*}

Integration tables:
\begin{align*}
  n =& 2 \\
  c_1 =& 0, \: c_0 = \sqrt{10} \\
  d_2 =& 1, \: d_1 = 10, \: d_0 = 100 \\
\end{align*}

Mean square value:
\begin{equation*}
  E[x^2] = \frac{c_1^2 d_0 + c_0^2 d_2}{2 d_0 d_1 d_2} = \frac{10}{2 \cdot 100 \cdot 10 \cdot 1} = 0.005
\end{equation*}