# Solution {-}

PVA Markov model

In [1]:
from sympy import Matrix, symbols, sqrt, eye, integrate, inverse_laplace_transform

s, dt, beta, q = symbols('s \Delta{t} beta q', positive=True)

F = Matrix([[0, 1, 0],
            [0, 0, 1],
            [0, 0, -beta]])

G = Matrix([[0],
            [0],
            [sqrt(q)]])

phi = inverse_laplace_transform((s*eye(3) - F).inv(), s, dt)
phi

Matrix([
[1, \Delta{t}, \Delta{t}/beta - 1/beta**2 + exp(-\Delta{t}*beta)/beta**2],
[0,         1,                        1/beta - exp(-\Delta{t}*beta)/beta],
[0,         0,                                      exp(-\Delta{t}*beta)]])

In [2]:
# Process noise
Q = integrate(phi@G@G.T@phi.T, dt)
Q

Matrix([
[\Delta{t}**3*q/(3*beta**2) - \Delta{t}**2*q/beta**3 + \Delta{t}*q/beta**4 + (-4*\Delta{t}*beta**5*q*exp(-\Delta{t}*beta) - beta**4*q*exp(-2*\Delta{t}*beta))/(2*beta**9), \Delta{t}**2*q/(2*beta**2) - \Delta{t}*q/beta**3 + (beta**4*q*exp(-2*\Delta{t}*beta) + (2*\Delta{t}*beta**5*q - 2*beta**4*q)*exp(-\Delta{t}*beta))/(2*beta**8), (-2*\Delta{t}*beta**3*q*exp(-\Delta{t}*beta) - beta**2*q*exp(-2*\Delta{t}*beta))/(2*beta**5)],
[          \Delta{t}**2*q/(2*beta**2) - \Delta{t}*q/beta**3 + (beta**4*q*exp(-2*\Delta{t}*beta) + (2*\Delta{t}*beta**5*q - 2*beta**4*q)*exp(-\Delta{t}*beta))/(2*beta**8),                                                        \Delta{t}*q/beta**2 + (4*beta**3*q*exp(-\Delta{t}*beta) - beta**3*q*exp(-2*\Delta{t}*beta))/(2*beta**6),           (-2*beta**2*q*exp(-\Delta{t}*beta) + beta**2*q*exp(-2*\Delta{t}*beta))/(2*beta**4)],
[                                                                            (-2*\Delta{t}*beta**3*q*exp(-\Delta{t}*beta) - beta**2*q*exp(-

In [3]:
from numpy import array, sqrt, set_printoptions
from lib.vanloan import numeval

set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

# System conditions
dt = 0.1
beta = 0.2
q = 10

F = array([[0, 1, 0],
           [0, 0, 1],
           [0, 0, -beta]])

G = array([[0],
           [0],
           [sqrt(q)]])

# Numerical evaulation
[phi, Q] = numeval(F, G, dt)

# Transition matrix
print(phi)

# Process noise covariance matrix
print(Q)

[[1.000 0.100 0.005]
 [0.000 1.000 0.099]
 [0.000 0.000 0.980]]
[[0.000 0.000 0.002]
 [0.000 0.003 0.049]
 [0.002 0.049 0.980]]
